"""
OpenEye -> HuggingFace Hub integration.
Pushes trajectory JSONL and a dataset card to a HF dataset repository.
Uses the HF Hub HTTP API directly — no huggingface_hub SDK required.
"""

import json
import logging
import os
import random
import statistics
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

try:
    from state import get_db
except ImportError:
    get_db = None

logger = logging.getLogger(__name__)

HF_API = "https://huggingface.co/api"
HF_BASE = "https://huggingface.co"

HF_MAX_RETRIES = int(os.getenv("OPENEYE_HF_MAX_RETRIES", "3"))
HF_BACKOFF_BASE = float(os.getenv("OPENEYE_HF_BACKOFF_BASE", "1.0"))
RETRYABLE_STATUS = {408, 425, 429, 500, 502, 503, 504}


def build_dataset_card(trajectories: List[Dict], repo_id: str, tags: List[str]) -> str:
    """Build a HuggingFace dataset card (YAML front matter + markdown body)."""
    all_tags = sorted(set(["openeye", "procedure-verification"] + (tags or [])))
    rewards = [t.get("reward_signal") for t in trajectories if t.get("reward_signal") is not None]
    models = sorted(set(t.get("model", "unknown") for t in trajectories))
    procedures = set()
    for t in trajectories:
        meta = t.get("openeye_meta", {})
        for tag in meta.get("tags", []):
            if tag not in ("openeye", "completed", "abandoned", "error"):
                procedures.add(tag)

    completed = sum(1 for t in trajectories if t.get("completed"))
    abandoned = len(trajectories) - completed

    # YAML front matter
    tags_yaml = "\n".join(f"  - {t}" for t in all_tags)
    yaml_block = f"""---
license: mit
task_categories:
  - text-generation
language:
  - en
tags:
{tags_yaml}
---"""

    # Stats
    stats_lines = [f"- **Trajectories:** {len(trajectories)} ({completed} completed, {abandoned} abandoned)"]
    if procedures:
        stats_lines.append(f"- **Procedures:** {', '.join(sorted(procedures))}")
    stats_lines.append(f"- **Models:** {', '.join(models)}")
    if rewards:
        stats_lines.append(f"- **Reward signal:** min={min(rewards):.2f}, max={max(rewards):.2f}, "
                           f"mean={statistics.mean(rewards):.2f}")
        if len(rewards) >= 4:
            sorted_r = sorted(rewards)
            p25 = sorted_r[len(sorted_r) // 4]
            p75 = sorted_r[3 * len(sorted_r) // 4]
            stats_lines.append(f"- **Reward percentiles:** p25={p25:.2f}, p75={p75:.2f}")

    stats = "\n".join(stats_lines)

    snippet = f'''```python
from datasets import load_dataset
ds = load_dataset("{repo_id}")
print(ds["train"][0]["conversations"])
```'''

    return f"""{yaml_block}

# {repo_id.split("/")[-1]}

Agent session trajectories generated by [OpenEye](https://github.com/dumbspacecookie/openeye).

## Statistics

{stats}

## Usage

{snippet}

## Format

Each row contains a `conversations` array in ShareGPT format and an `openeye_meta` object
with visual session ID, reward signal, and procedure tags.

---

*Generated with [OpenEye](https://github.com/dumbspacecookie/openeye)*
"""


def _hf_request_once(method: str, url: str, token: str, body: Any = None,
                     content_type: str = "application/json") -> Dict:
    """One HF API attempt. Raises on HTTP errors and network errors."""
    if isinstance(body, dict) or isinstance(body, list):
        data = json.dumps(body).encode("utf-8")
    elif isinstance(body, bytes):
        data = body
    elif isinstance(body, str):
        data = body.encode("utf-8")
    else:
        data = None

    req = urllib.request.Request(url, data=data, headers={
        "Authorization": f"Bearer {token}",
        "Content-Type": content_type,
    }, method=method)

    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read()
        if not raw:
            return {}
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return {"_raw": raw.decode("utf-8", errors="replace")}


def _hf_request(method: str, url: str, token: str, body: Any = None,
                content_type: str = "application/json",
                max_retries: int = HF_MAX_RETRIES) -> Dict:
    """Authenticated HF Hub request with retry on transient failures.

    Terminal errors (401, 403, 404, 422) raise immediately.
    Retryable errors (408, 429, 5xx, network) back off exponentially.
    """
    last_exc: Optional[Exception] = None
    for attempt in range(max_retries + 1):
        try:
            return _hf_request_once(method, url, token, body, content_type)
        except urllib.error.HTTPError as e:
            if e.code == 401:
                raise PermissionError(
                    "Invalid HuggingFace token. Get one at https://huggingface.co/settings/tokens")
            if e.code == 403:
                raise PermissionError(
                    "Permission denied. Check that the token has write access.")
            if e.code in RETRYABLE_STATUS and attempt < max_retries:
                delay = HF_BACKOFF_BASE * (2 ** attempt) + random.uniform(0, 0.5)
                logger.info("HF %s attempt %d/%d returned %d; retrying in %.1fs",
                            method, attempt + 1, max_retries + 1, e.code, delay)
                time.sleep(delay)
                last_exc = e
                continue
            body_text = e.read().decode("utf-8", errors="replace") if e.fp else ""
            raise RuntimeError(f"HuggingFace API error {e.code}: {body_text}")
        except (urllib.error.URLError, OSError, TimeoutError) as e:
            if attempt < max_retries:
                delay = HF_BACKOFF_BASE * (2 ** attempt) + random.uniform(0, 0.5)
                logger.info("HF %s attempt %d/%d network error (%s); retrying in %.1fs",
                            method, attempt + 1, max_retries + 1, e, delay)
                time.sleep(delay)
                last_exc = e
                continue
            raise ConnectionError("HuggingFace Hub unreachable. Check your connection.")

    if last_exc:
        raise ConnectionError(f"HuggingFace Hub unreachable after {max_retries + 1} attempts: {last_exc}")
    raise ConnectionError("HuggingFace Hub unreachable.")


def _load_trajectories_as_list(completed_only: bool = True) -> List[Dict]:
    """Load trajectories from DB as a list of dicts (not JSONL)."""
    db = get_db()
    with db._lock:
        q = "SELECT * FROM trajectories"
        if completed_only:
            q += " WHERE completed=1"
        q += " ORDER BY created_at"
        cursor = db._conn.execute(q)
        rows = cursor.fetchall()

    result = []
    for row in rows:
        t = dict(row)
        try:
            t["conversations"] = json.loads(t["conversations"])
        except (json.JSONDecodeError, TypeError):
            t["conversations"] = []
        try:
            t["openeye_meta"] = {
                "visual_session_id": t.get("visual_session_id"),
                "tenant_id": t.get("tenant_id"),
                "reward_signal": t.get("reward_signal"),
                "tags": json.loads(t["tags"]) if t.get("tags") else [],
            }
        except (json.JSONDecodeError, TypeError):
            t["openeye_meta"] = {}
        result.append(t)
    return result


def push_trajectories_to_hub(
    repo_id: str,
    hf_token: str,
    private: bool = False,
    tags: Optional[List[str]] = None,
    dry_run: bool = False,
    completed_only: bool = True,
) -> Dict[str, Any]:
    """Export completed trajectories and push to a HuggingFace dataset repo."""
    trajectories = _load_trajectories_as_list(completed_only)

    if not trajectories:
        raise ValueError("No completed trajectories to push. Run a session first.")

    if dry_run:
        return {"would_push": len(trajectories), "repo_id": repo_id, "dry_run": True}

    # Create or verify dataset repo
    repo_name = repo_id.split("/")[-1] if "/" in repo_id else repo_id
    _hf_request("POST", f"{HF_API}/repos/create", hf_token,
                body={"type": "dataset", "name": repo_name, "private": private})

    # Build JSONL
    jsonl_lines = []
    for t in trajectories:
        entry = {
            "conversations": t["conversations"],
            "timestamp": t.get("created_at"),
            "model": t.get("model"),
            "completed": bool(t.get("completed")),
            "openeye_meta": t.get("openeye_meta", {}),
        }
        jsonl_lines.append(json.dumps(entry, ensure_ascii=False))
    jsonl_bytes = "\n".join(jsonl_lines).encode("utf-8")

    # Build dataset card
    card = build_dataset_card(trajectories, repo_id, tags or [])
    card_bytes = card.encode("utf-8")

    # Upload files
    upload_base = f"{HF_BASE}/api/datasets/{repo_id}/upload/main"
    _hf_request("PUT", f"{upload_base}/trajectories.jsonl", hf_token,
                body=jsonl_bytes, content_type="application/octet-stream")
    _hf_request("PUT", f"{upload_base}/README.md", hf_token,
                body=card_bytes, content_type="application/octet-stream")

    url = f"https://huggingface.co/datasets/{repo_id}"
    return {"pushed": len(trajectories), "repo_id": repo_id, "url": url, "dry_run": False}
